[FT-4738] Merge `develop` into `procurify-development`
procurify/django-star-ratings pull request #23
Opened 2024-02-06 21:07 UTC by mtucciarone

2024-02-06 21:08 UTC, mtucciarone commented
This requires https://github.com/procurify/django-star-ratings/pull/21 to be merged in as well

2024-02-07 20:20 UTC, steve-curran commented
Please add a description to provide context for these changes and a ticket. 

This repo settings is also missing branch protection, which can result in unreviewed commits, which I believe is a violation of our SoC controls.

2024-02-07 20:21 UTC, steve-curran requested changes
Missing description - branch protection rules need to be updated. See comment [above.](https://github.com/procurify/django-star-ratings/pull/23#issuecomment-1932801487)

2024-02-07 21:06 UTC, mtucciarone commented
@steve-curran i don't have rights on this specific branch -- @neilpower can probably help here.

2024-02-07 21:43 UTC, steve-curran reviewed
Some comments. 

I've very little context to review this PR other than it aims to resolve vulnerabilities in dependencies. 

e.g - I see behavior changes [here](https://github.com/procurify/django-star-ratings/pull/23/files#diff-baa8e65b68e5642f3466cf656dcffedee24abdd414e96d78d88e1a6e5aded686R44)  but I do not know why they are being made.

2024-02-07 21:43 UTC, steve-curran commented on .github/dependabot.yml
> +  - package-ecosystem: "npm" # See documentation for possible values
Why do we need npm here? 

I see a package.json that refers to a sass build process but I don't see any of the associated directories. Is the re a pipeline that runs for this repo to produce assets?

2024-02-07 21:43 UTC, steve-curran commented on .github/dependabot.yml
> +  - package-ecosystem: "bundler" # See documentation for possible values
Does this repo have ruby deps?

2024-02-07 21:43 UTC, steve-curran commented on star_ratings/views.py
> +                return_url = return_url[0]
What happens when the list is empty?

2024-02-07 21:43 UTC, steve-curran commented on tests/base.py
> +        We need to use a different Foo class if the model rating model is switched out (as it needs UUID).
What is a `Foo` class?

2024-02-07 21:43 UTC, steve-curran commented on tests/base.py
> +        self.bar_model = apps.get_model(app_label=bar_app, model_name=bar_model_name)
missing newline terminator here as flagged by github. Same on many other files

2024-02-07 21:57 UTC, nav commented
Hey Procurify team, I am apparently subscribed to this repo. @steve-curran For context, this was a fork of https://pypi.org/project/django-star-ratings/ done by Vinny (IIRC) so most of the code is from the parent repo.

2024-02-08 08:17 UTC, neilpower commented
@steve-curran @mtucciarone - We have branch protection rules for the default branch `develop` but not for the branch `procurify-development`. Should we be merging into `develop` here instead or should our default branch be updated?

2024-02-08 15:51 UTC, steve-curran commented
> Hey Procurify team, I am apparently subscribed to this repo. @steve-curran For context, this was a fork of https://pypi.org/project/django-star-ratings/ done by Vinny (IIRC) so most of the code is from the parent repo.

Thanks @nav, I appreciate the context here. - I'll work with @neilpower to figure out your lingering access.

2024-02-08 16:33 UTC, mtucciarone commented
@neilpower it would make sense to just use `develop` as the branch that `procurifydevelopment` refers to in its packages for pulling in `django-star-ratings`

2024-02-08 17:49 UTC, mtucciarone commented
@steve-curran Since `develop` has been the maintained branch for this repo, there's been some upstreams pulls from the fork to ensure that our version upgrades and bugfixes from the fork also make their way into this codebase and repository. About 8 months ago I did an update to this code to remediate all of the github security issues which came with code changes from the fork merge. I did not divert from any of the incoming code nor did I explicitly change any code functionality in said pull. Since this repo is being targeted for deletion in our sunsetting plan, I'd like to focus on the scope here of removing our vulnerabilities over code quality that we're not maintaining at the moment.

2024-02-09 00:35 UTC, steve-curran commented
> @neilpower it would make sense to just use `develop` as the branch that `procurifydevelopment` refers to in its packages for pulling in `django-star-ratings`

@mtucciarone - this would make sense to me

2024-02-09 00:36 UTC, steve-curran approved these changes
After getting more context in backend chapter meeting I'm ok to approve this. 

I would like to see us get off this as soon as possible. I've added an item to our 1:1 @neilpower to see where we are at in this regard.

2024-02-26 15:23 UTC, merged